import { boolean, foreignKey, index, integer, pgTable, real, smallint, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core"
import { fincas } from "./fincas.js"
import { configCalidadAnimal, configRazas, configTiposExplotacion } from "./config.js"
import { grupos, hierros, lotes, potreros, propietarios, sectores } from "./maestros.js"
import { usuarios } from "./auth.js"

export const animales = pgTable(
  "animales",
  {
    id: text("id").primaryKey(),
    fincaId: text("finca_id").notNull().references(() => fincas.id),
    codigo: varchar("codigo", { length: 20 }).notNull(),
    nombre: varchar("nombre", { length: 100 }).default(""),
    fechaNacimiento: integer("fecha_nacimiento"),
    fechaCompra: integer("fecha_compra"),
    sexoKey: integer("sexo_key").default(0),
    tipoIngresoId: integer("tipo_ingreso_id").default(0),
    madreId: text("madre_id"),
    codigoMadre: text("codigo_madre").default(""),
    indTransferenciaEmbriones: integer("ind_transferencia_embriones").default(0),
    codigoDonadora: text("codigo_donadora").default(""),
    tipoPadreKey: integer("tipo_padre_key").default(0),
    padreId: text("padre_id"),
    codigoPadre: text("codigo_padre").default(""),
    codigoPajuela: text("codigo_pajuela").default(""),
    configRazasId: text("config_razas_id").references(() => configRazas.id),
    potreroId: text("potrero_id").references(() => potreros.id),
    sectorId: text("sector_id").references(() => sectores.id),
    loteId: text("lote_id").references(() => lotes.id),
    grupoId: text("grupo_id").references(() => grupos.id),
    hierroId: text("hierro_id").references(() => hierros.id),
    propietarioId: text("propietario_id").references(() => propietarios.id),
    calidadAnimalId: text("calidad_animal_id").references(() => configCalidadAnimal.id),
    precioCompra: real("precio_compra").default(0),
    pesoCompra: real("peso_compra").default(0),
    codigoRfid: text("codigo_rfid").default(""),
    codigoArete: text("codigo_arete").default(""),
    codigoQr: text("codigo_qr").default(""),
    saludAnimalKey: integer("salud_animal_key").default(0),
    estadoAnimalKey: integer("estado_animal_key").default(0),
    indDescartado: integer("ind_descartado").default(0),
    tipoExplotacionId: text("tipo_explotacion_id").references(() => configTiposExplotacion.id),
    transferenciaEmbrion: boolean("transferencia_embrion").default(false).notNull(),
    donadoraId: text("donadora_id"),
    tipoConcepcionPadre: text("tipo_concepcion_padre"),
    categoriaReproductiva: text("categoria_reproductiva"),
    tatuado: boolean("tatuado").default(false).notNull(),
    herrado: boolean("herrado").default(false).notNull(),
    descornado: boolean("descornado").default(false).notNull(),
    numeroPezones: smallint("numero_pezones"),
    comentarios: text("comentarios"),
    activo: integer("activo").default(1).notNull(),
    usuarioCreadoPor: text("usuario_creado_por").references(() => usuarios.id),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
    version: integer("version").default(1).notNull(),
  },
  (t) => [
    foreignKey({ columns: [t.madreId], foreignColumns: [t.id] }),
    foreignKey({ columns: [t.padreId], foreignColumns: [t.id] }),
    foreignKey({ columns: [t.donadoraId], foreignColumns: [t.id] }),
    uniqueIndex("uq_animales_finca_codigo").on(t.fincaId, t.codigo),
    index("idx_animales_finca_activo").on(t.fincaId, t.activo),
    index("idx_animales_madre").on(t.madreId),
    index("idx_animales_padre").on(t.padreId),
  ],
)

export type Animal = typeof animales.$inferSelect
export type NuevoAnimal = typeof animales.$inferInsert
